backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "/src/images" # Media files will be stored in the repo under /src/images/uploads
public_folder: "../images" # So that the images get imported correctly in the markdown files

collections:
  - label: "MHP" # Used in the UI
    name: "MHP" # Used in routes, e.g., /admin/collections/MHP
    editor:
      preview: false
    files:
      - label: "Social Links" # Used in the UI
        name: "socials" # Used in routes, e.g., /admin/collections/MHP
        file: "/src/markdown/socials.md" # What the markdown is called
        fields:
          - { label: Instagram Link, name: instagram, widget: string }
          - { label: Facebook Link, name: facebook, widget: string }
          - { label: LinkedIn Link, name: linkedIn, widget: string }
          - { label: Github Link, name: github, widget: string }

      - label: "Index"
        name: "index"
        file: "/src/markdown/index.md"
        fields:
          - { label: Heading, name: heading, widget: string }
          - { label: Image, name: image, widget: image }
          - {
              label: SEO Page Description,
              name: meta_page_description,
              widget: text,
              required: false,
              hint: "This text will show up in the Google description of the page (The text under the link)",
            }
          - label: Info Blocks
            name: blocks
            widget: list
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Description, name: description, widget: text }
              - {
                  label: Button Text,
                  name: buttonText,
                  widget: string,
                  default: "",
                  required: false,
                }
              - { label: Image, name: image, widget: image }
              - {
                  label: Button Link,
                  name: href,
                  widget: string,
                  default: "",
                  required: false,
                }
              - {
                  label: ID for header,
                  name: id,
                  widget: string,
                  hint: "If you are not changing the header, don't mess with it!",
                }
          - label: Subteam Information Section
            name: subteams
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Description, name: description, widget: text }
              - {
                  label: Button Text,
                  name: button_text,
                  widget: string,
                  hint: "This could be used for recruiting text eg. Apply Here",
                  default: "",
                  required: false,
                }
              - {
                  label: Button Link,
                  name: button_href,
                  widget: string,
                  hint: "This could be used for a recruiting link eg. a google doc",
                  default: "",
                  required: false,
                }
          - label: Sponsor Section
            name: sponsors
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Image, name: image, widget: image }

      - label: "Team Page"
        name: "team"
        file: "/src/markdown/team.md"
        fields:
          - { label: Heading, name: heading, widget: string }
          - {
              label: Description,
              name: description,
              widget: text,
              default: "",
              required: false,
            }
          - {
              label: SEO Page Description,
              name: meta_page_description,
              widget: text,
              required: false,
              hint: "This text will show up in the Google description of the page (The text under the link)",
            }

          # - {
          #     label: mainPhoto,
          #     name: photo,
          #     widget: image,
          #     required: false
          #   }
          - label: Subteam
            name: subteam
            widget: list
            fields:
              - { label: SubteamName, name: subteamName, widget: text }
              - label: Team Members
                name: teamMembers
                widget: list
                fields:
                  - { label: Name, name: name, widget: string }
                  - { label: Degree, name: degree, widget: string }
                  - { label: Position, name: position, widget: string }
                  - { label: Photo, name: photo, widget: image }
                  - {
                      label: LinkedIn,
                      name: linkedIn,
                      widget: string,
                      default: "",
                      required: false,
                    }

      - label: "404"
        name: "404_page"
        file: "/src/markdown/404.md"
        fields:
          - {
              label: SEO Page Description,
              name: meta_page_description,
              widget: text,
              required: false,
              hint: "This text will show up in the Google description of the page (The text under the link)",
            }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subtext, name: subtext, widget: string }

      - label: "SubTeams Page"
        name: "subteams"
        file: "/src/markdown/subteams.md"
        fields:
          - { label: Heading, name: heading, widget: string }
          - {
              label: SEO Page Description,
              name: meta_page_description,
              widget: text,
              required: false,
              hint: "This text will show up in the Google description of the page (The text under the link)",
            }
          - label: SubTeams Info Blocks
            name: subteams
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Description, name: description, widget: text }
              - {
                  label: Button Text,
                  name: button_text,
                  widget: string,
                  hint: "This could be used for recruiting text eg. Apply Here",
                  default: "",
                  required: false,
                }
              - {
                  label: Button Link,
                  name: button_href,
                  widget: string,
                  hint: "This could be used for a recruiting link eg. a google doc",
                  default: "",
                  required: false,
                }
              - { label: Image, name: image, widget: image }

      - label: "Bike Page"
        name: "bike"
        file: "/src/markdown/bike.md"
        fields:
          - { label: Heading, name: heading, widget: string }
          - {
              label: SEO Page Description,
              name: meta_page_description,
              widget: text,
              required: false,
              hint: "This text will show up in the Google description of the page (The text under the link)",
            }
          - label: Bike Info
            name: bikes
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - {
                  label: version,
                  name: version,
                  widget: number,
                  hint: "eg. 2.5 or 3",
                }
              - { label: Description, name: description, widget: text }
              - {
                  label: Start Year,
                  name: start_year,
                  widget: number,
                  hint: "eg. 2020",
                }
              - {
                  label: End Year,
                  name: end_year,
                  widget: number,
                  hint: "eg. 2020",
                }
              - {
                  label: Top Speed,
                  name: top_speed_km,
                  widget: string,
                  hint: "eg. a string such as '81.2' or 'unknown'",
                }
              - { label: Image, name: image, widget: image }
