backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "/src/images" # Media files will be stored in the repo under /src/images/uploads
public_folder: "../images" # So that the images get imported correctly in the markdown files

collections:
  - label: "MHP" # Used in the UI
    name: "MHP" # Used in routes, e.g., /admin/collections/MHP
    editor:
      preview: false
    files:
      - label: "Social Links" # Used in the UI
        name: "socials" # Used in routes, e.g., /admin/collections/MHP
        file: "/src/markdown/socials.md" # What the markdown is called
        fields:
          - { label: Instagram Link, name: instagram, widget: string }
          - { label: Facebook Link, name: facebook, widget: string }
          - { label: LinkedIn Link, name: linkedIn, widget: string }
          - { label: Github Link, name: github, widget: string }
          - { label: TikTok Link, name: tiktok, widget: string }

      - label: "Index"
        name: "index"
        file: "/src/markdown/index.md"
        fields:
          - { label: Heading, name: heading, widget: string }
          - { label: Image, name: image, widget: image }
          - label: SEO Page Description
            name: meta_page_description
            required: false
            hint: "This text will show up in the Google description of the page (The text under the link)"
          - label: Recruitment Open
            name: recruitment_open
            widget: boolean
            hint: Toggle this on when recruitments are open.
          - label: Recruitment Link
            name: recruitment_link
            widget: string
            hint: Link to the recruitment form, or perhaps the general recruitment section of join us page. Whichever is more convenient and provides the most information to applicants.
          - label: Recruitment Info Link
            name: recruitment_info
            widget: string
            hint: Link to a page/document where people can find out about the recruitment and open positions.
          - label: Recruitment Description
            name: recruitment_description
            widget: text
          - label: Splash Section
            name: splash
            widget: object
            hint: Splash section, including video
            fields:
              - { label: Splash Heading, name: heading, widget: string }
              - { label: Splash Body, name: body, widget: string }
              - label: Trailer Embed Link
                name: trailer_link
                widget: string
                hint: This link MUST be an embed link e.g. https://youtube.com/embed/someVideoId, otherwise it may not work.
          - label: Sponsor Section
            name: sponsors
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Link to Sponsor, name: link, widget: string }
              - { label: Image, name: image, widget: image }

      - label: "About Page"
        name: "about"
        file: "/src/markdown/about.md"
        fields:
          - { label: Heading, name: heading, widget: string }
          - label: SEO Page Description
            name: meta_page_description
            required: false
            hint: "This text will show up in the Google description of the page (The text under the link)"
          - label: Info Blocks
            name: blocks
            widget: list
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Description, name: description, widget: text }
              - {
                  label: Button Text,
                  name: buttonText,
                  widget: string,
                  default: "",
                  required: false,
                }
              - { label: Image, name: image, widget: image }
              - {
                  label: Button Link,
                  name: href,
                  widget: string,
                  default: "",
                  required: false,
                }
              - {
                  label: ID for header,
                  name: id,
                  widget: string,
                  hint: "If you are not changing the header, don't mess with it!",
                }
          - label: Our Values Section
            name: our_values
            widget: list
            fields:
              - label: Heading
                name: heading
              - label: Content
                name: content
                widget: text
          - label: Subteam Information Section
            name: subteams
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Description, name: description, widget: text }
              - {
                  label: Button Text,
                  name: button_text,
                  widget: string,
                  hint: "This could be used for recruiting text eg. Apply Here",
                  default: "",
                  required: false,
                }
              - {
                  label: Button Link,
                  name: button_href,
                  widget: string,
                  hint: "This could be used for a recruiting link eg. a google doc",
                  default: "",
                  required: false,
                }
              - {
                  label: Anchor ID,
                  name: id,
                  widget: string,
                  hint: "Used to jump to the appropriate section in the subteam page. Must match the ID in the subteam page.",
                  default: "",
                }

      - label: "Team Page"
        name: "team"
        file: "/src/markdown/team.md"
        fields:
          - { label: Heading, name: heading, widget: string }
          - {
              label: Description,
              name: description,
              widget: text,
              default: "",
              required: false,
            }
          - {
              label: SEO Page Description,
              name: meta_page_description,
              widget: text,
              required: false,
              hint: "This text will show up in the Google description of the page (The text under the link)",
            }

          # - {
          #     label: mainPhoto,
          #     name: photo,
          #     widget: image,
          #     required: false
          #   }
          - label: Subteam
            name: subteam
            widget: list
            fields:
              - { label: SubteamName, name: subteamName, widget: text }
              - label: Team Members
                name: teamMembers
                widget: list
                fields:
                  - { label: Name, name: name, widget: string }
                  - { label: Degree, name: degree, widget: string }
                  - { label: Position, name: position, widget: string }
                  - { label: Photo, name: photo, widget: image }
                  - {
                      label: LinkedIn,
                      name: linkedIn,
                      widget: string,
                      default: "",
                      required: false,
                    }

      - label: "404"
        name: "404_page"
        file: "/src/markdown/404.md"
        fields:
          - {
              label: SEO Page Description,
              name: meta_page_description,
              widget: text,
              required: false,
              hint: "This text will show up in the Google description of the page (The text under the link)",
            }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subtext, name: subtext, widget: string }

      - label: "SubTeams Page"
        name: "subteams"
        file: "/src/markdown/subteams.md"
        fields:
          - { label: Heading, name: heading, widget: string }
          - {
              label: SEO Page Description,
              name: meta_page_description,
              widget: text,
              required: false,
              hint: "This text will show up in the Google description of the page (The text under the link)",
            }
          - label: SubTeams Info Blocks
            name: subteams
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Description, name: description, widget: text }
              - {
                  label: Button Text,
                  name: button_text,
                  widget: string,
                  hint: "This could be used for recruiting text eg. Apply Here",
                  default: "",
                  required: false,
                }
              - {
                  label: Button Link,
                  name: button_href,
                  widget: string,
                  hint: "This could be used for a recruiting link eg. a google doc",
                  default: "",
                  required: false,
                }
              - { label: Image, name: image, widget: image }
              - {
                  label: Anchor ID,
                  name: id,
                  widget: string,
                  hint: "Used to jump to the appropriate subteam.",
                  default: "",
                }

      - label: "Bike Page"
        name: "bike"
        file: "/src/markdown/bike.md"
        fields:
          - { label: Heading, name: heading, widget: string }
          - {
              label: SEO Page Description,
              name: meta_page_description,
              widget: text,
              required: false,
              hint: "This text will show up in the Google description of the page (The text under the link)",
            }
          - label: Bike Info
            name: bikes
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - {
                  label: version,
                  name: version,
                  widget: number,
                  hint: "eg. 2.5 or 3",
                }
              - { label: Description, name: description, widget: text }
              - {
                  label: Start Year,
                  name: start_year,
                  widget: number,
                  hint: "eg. 2020",
                }
              - {
                  label: End Year,
                  name: end_year,
                  widget: number,
                  hint: "eg. 2020",
                }
              - {
                  label: Top Speed,
                  name: top_speed_km,
                  widget: string,
                  hint: "eg. a string such as '81.2' or 'unknown'",
                }
              - { label: Image, name: image, widget: image }

      - label: "Competitions Page"
        name: "competitions"
        file: "/src/markdown/competitions.md"
        fields:
          - { label: Heading, name: heading, widget: string }
          - {
              label: SEO Page Description,
              name: meta_page_description,
              widget: text,
              required: false,
              hint: "This text will show up in the Google description of the page (The text under the link)",
            }
          - label: Competitions Info Blocks
            name: blocks
            widget: list
            fields:
              - { label: Name, name: heading, widget: string }
              - { label: Description, name: description, widget: text }
              - {
                  label: Button Text,
                  name: buttonText,
                  widget: string,
                  hint: "Label to link the competition's home page.",
                  default: "",
                  required: false,
                }
              - {
                  label: Button Link,
                  name: href,
                  widget: string,
                  hint: "Link to the competition's home page.",
                  default: "",
                  required: false,
                }
              - { label: Image, name: image, widget: image }
              - {
                  label: Anchor ID,
                  name: id,
                  widget: string,
                  hint: "Used to jump to the appropriate section.",
                  default: "",
                }

      - label: "Outreach Page"
        name: "outreach"
        file: "/src/markdown/outreach.md"
        fields:
          - { label: Heading, name: heading, widget: string }
          - {
              label: SEO Page Description,
              name: meta_page_description,
              widget: text,
              required: false,
              hint: "This text will show up in the Google description of the page (The text under the link)",
            }
          - label: Outreach Info Blocks
            name: blocks
            widget: list
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Description, name: description, widget: text }
              - {
                  label: Button Text,
                  name: buttonText,
                  widget: string,
                  default: "",
                  required: false,
                }
              - { label: Image, name: image, widget: image }
              - {
                  label: ID for header,
                  name: id,
                  widget: string,
                  hint: "If you are not changing the header, don't mess with it!",
                }
              - {
                  label: Button Link,
                  name: href,
                  widget: string,
                  default: "",
                  required: false,
                }

          - label: Outreach Reviews
            name: reviews
            widget: list
            fields:
              - {
                  label: Person,
                  name: person,
                  widget: string,
                  hint: "The person / organization who said the quote",
                }
              - { label: Quote, name: quote, widget: string }

      - label: "Recruitment Page"
        name: "recruitment"
        file: "/src/markdown/joinUs.md"
        fields:
          - { label: Heading, name: heading, widget: string }
          - {
              label: SEO Page Description,
              name: meta_page_description,
              widget: text,
              required: false,
              hint: "This text will show up in the Google description of the page (The text under the link)",
            }
          - label: Recruitment Categories
            name: recruitment_categories
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Currenrtly Open, name: is_open, widget: boolean }
              - {
                  label: Description (Open),
                  name: description,
                  widget: text,
                  hint: Description when recruitments are open.,
                }
              - {
                  label: Description (Closed),
                  name: description_closed,
                  widget: text,
                  hint: Description when recruitments are closed.,
                }
              - { label: Image, name: image, widget: image }
              - {
                  label: Application Link,
                  name: link,
                  widget: string,
                  hint: "Link to application form.",
                  default: "",
                  required: false,
                }
              - {
                  label: More Info Link,
                  name: more_info_link,
                  widget: string,
                  hint: "Link to more information about this category (e.g. position description).",
                  default: "",
                  required: false,
                }
              - {
                  label: Expression of Interest Link,
                  name: eoi_link,
                  widget: string,
                  hint: "Link to EOI form.",
                  default: "",
                  required: false,
                }
              - {
                  label: Anchor ID,
                  name: id,
                  widget: string,
                  hint: "Used to jump to the appropriate section.",
                  default: "",
                }
          - label: Recruitment Process Section
            name: recruitment_process
            widget: list
            fields:
              - label: Heading
                name: heading
              - label: Content
                name: content
                widget: text
          - label: FAQ Section
            name: FAQs
            widget: list
            fields:
              - label: Question
                name: question
              - label: Answer
                name: answer
                widget: text
